version: '3'
services: 
  site:
    build: './site'
    ports: 
      - 80:80
    links:
      - 'users'

    # Use it only for dev purposes
    # volumes:
    #   - './site/data:/var/www/html'
  users:
    build: './users'
    
    # Use it only for dev purposes
    # volumes:
    #  - './users/data:/var/www/html'